### ISSUE TITLE
No portal id when faculty login

### ISSUE THREAD

**Issue by c910335** [davy-tw/omniauth-ncu-portal-openid#1]
as title
request.env['omniauth.auth'].info.to_hash.to_s:
```
{"user_roles"=>"[\"ROLE_USER\",\"ROLE_FACULTY\",\"ROLE_LDAP\"]", "name"=>nil}
```

**Comment by davy-tw** [comment]
Use `request.env['omniauth.auth'].uid` to get the uid assigned by portal instead of getting portal account name.

This problem due to portal itself is not providing the account name when faculty account is logging-in.
If you are logging-in with student account, you can get `student_id` from info that portal give back, but there always no any account name here and even OpenID spec.
Providing account name is not admit from OpenID spec, only thing you can identify is the uid assigned by the OpenID provider.

**Comment by c910335** [comment]
👍
